{% set version = "2.0.1" %}

package:
  name: xlrd
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xlrd/xlrd-{{ version }}.tar.gz
  sha256: f72f148f54442c6b056bf931dbc34f986fd0c3b0b6b5a58d013c9aef274d0c88

build:
  number: 4
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  files:
    - test.xls

about:
  home: 'http://www.python-excel.org/'
  license: "BSD-3-Clause AND BSD-4-Clause"
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Library for developers to extract data from Microsoft Excel (tm) spreadsheet files'
  doc_url: http://xlrd.readthedocs.io/en/stable/
  dev_url: https://github.com/python-excel/xlrd/

extra:
  recipe-maintainers:
   - cokelaer
   - notestaff
   - mjhoptics
