{% set version = "2.0.0" %}

package:
  name: xlrd
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xlrd/xlrd-{{ version }}.tar.gz
  sha256: e1ae0dbdb0a4888e381255f9aefe3efcd7ea64a35666e7a03c3f3c9e4b44641b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  files:
    - test.xlsx

about:
  home: http://www.python-excel.org/
  license: BSD-3-Clause AND BSD-4-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Library for developers to extract data from Microsoft Excel (tm) spreadsheet files
  doc_url: http://xlrd.readthedocs.io/en/stable/
  dev_url: https://github.com/python-excel/xlrd/

extra:
  recipe-maintainers:
    - cokelaer
    - notestaff
