travis:
  secure:
    BINSTAR_TOKEN: pxSnlHn/I7qDh95ZRcjC0mp0pKU+Z1CmPtKkkQiy1sh06zCuoY0RmVogLQhIxATA1+g0hdVmQYyJC0SlShV4onFL0oMa9gn2C2mzvJRGtqcdttbxvXeymw9MBvY/mhapwy2T+rOtsDW44Wmni5PGfYR8ZHJ+7Ol4ISs5ZqOwlaW8toVpfs4hlx28ztHDRjMtJux3Q54klKYD+wBf2geC1dGyfJS52tfLZDwDOZ8e0FfVp6IhKbaD5Fz7Q2bkEerV0ro84dQ/pw1moIPvLbnvovRAJnHQIVWfoPjQuSFJnMutRYZjUQX+PNCyqGgpbNZdYnuNi0m5226+8j+H69jwd1xGq8HaeVstt5MhK9+Y+ia3pUV5XfuzL513rUlF6TcBCiSeoZ95WAvDpIRYwu8rPk4E/8sPEg+ra5Jl6NTk5jw3ZVkcBggLMfobgjkWmqYj1t/KpHsJZHgKs2DcPBcT4dgK/Jhg1kr8waPAmICGgYS5z1eUEj+A7IsAdg5vme8IOfraqsCaK8VHvVC42wneoWQFHtC9PEJwSb/vEogg5v2jMXaj8n7vGQCuChClAVzt05p1nDOZH3U+GbxrwMR1mjBgLAEsSxln3usI+ISobkQaNe+kuVc8p6I69xc0gg6tRW+/A8r9bvd3XloYlf0HPMdRTz9JO7HYvEJclfDXDPE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
